### PR TITLE
Add flow and modernize syntax

### PR DESCRIPTION
**Pull request by vforge**

### CODE REVIEW

**Comment by hakubo** [comment]
@Wikia/iwing @vforge I know npmtrends is knida shitty way to look at it. I'm sure we could find other evidences but it looks like TS is what will be adopted more in future not Flow.
https://www.npmtrends.com/flow-bin-vs-typescript

Could we have a discussions about this, before we land this PR?

**Comment by hakubo** [comment]
"TS because of how slow and non-optional it is"
- https://iamturns.com/typescript-babel/ - for development we can just use babel to compile TS, so it ain't slow
- non-optional - nope, TS is very much optional - you can type what you want and not type things that you don't

**Comment by nmonterroso** [comment]
My 2 cents:

Our experience on CAKE when we tried this is documented in [confluence](https://wikia-inc.atlassian.net/wiki/spaces/CAKE/pages/110593317/TypeScript+Experimentation). At the time the biggest issue we had was that TypeScript was optional **as long as TypeScript modules were only used from other TypeScript modules**. This made it a requirement for all of our code to either be TS or create defs for everything (even if they are dummy defs) since otherwise we couldn't import non-TS modules from TS modules. There are [numerous](https://github.com/microsoft/typescript/issues/3019) [issues](https://github.com/Microsoft/TypeScript/issues/2709) on this in Github around the time we tried TS.

>  I know npmtrends is knida shitty way to look at it. I'm sure we could find other evidences but it looks like TS is what will be adopted more in future not Flow.

As far as popularity goes, I think it's a good indicator. From looking at stackoverflow, for example, there are ~600 posts tagged with [flow](https://stackoverflow.com/questions/tagged/flow) (some aren't for flowjs, the name is pretty generic), while there are ~68k posts tagged with [typescript](https://stackoverflow.com/questions/tagged/typescript).

If we could overcome the issues we encountered during our trial on the CAKE team, I would be more onboard with choosing TS over Flow. From a quick Google search, it seems like there is now an `--allowJs` [compiler flag](https://www.typescriptlang.org/docs/handbook/compiler-options.html). There's also [`dts-gen`](https://github.com/Microsoft/dts-gen), though that hasn't been updated in a long time. Might be worth exploring.

@hakubo - do you have any examples of projects you've worked on that have migrated from es6 to TS, without doing the whole migration in one changeset? I believe the @Wikia/cake team is also thirsty for types (at least back when I was on the team), so a tool with a clear migration path would be preferred. I'd be happy for lore to be the guinea pigs for whatever we decide to start with. What do you think, @vforge ?

**Comment by nmonterroso** [comment]
I just tried out `create-react-app` with [typescript](https://facebook.github.io/create-react-app/docs/adding-typescript) and indeed I can use non-ts modules from ts modules. Magic!

**Comment by hakubo** [comment]
@nmonterroso not Magix, just compilers :)

**Comment by hakubo** [comment]
@vforge 
- looks like interoperability should not be a problem anymore
- speed of compile can be achieved with babel

What do you think?

**Comment by hakubo** [comment]
Additional benefit of TS we can have it in both React and Ember projects as there is this project: https://github.com/typed-ember/ember-cli-typescript

**Comment by vforge** [comment]
Let's check TS first!

**Pull request closed without merging**
